apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-sa
  namespace: lavinmq
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scale-role
  namespace: lavinmq
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["lavinmq-consumer"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-rolebinding
  namespace: lavinmq
subjects:
  - kind: ServiceAccount
    name: scaler-sa
roleRef:
  kind: Role
  name: scale-role
  apiGroup: rbac.authorization.k8s.io

