all:
  hosts:
    master:
      ansible_host: 10.78.225.110
      ip: 10.78.225.110
      access_ip: 10.78.225.110
    node01:
      ansible_host: 10.78.225.213
      ip: 10.78.225.213
      access_ip: 10.78.225.213
    node02:
      ansible_host: 10.78.225.80
      ip: 10.78.225.80
      access_ip: 10.78.225.80
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        node01:
        node02:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
