apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lavinmq-ingress
  namespace: lavinmq
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: lavinmq.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lavinmq
                port:
                  number: 15672

