apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lavinmq-pvc
  namespace: lavinmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # local-path-provisioner

